### ISSUE TITLE
Modular plugin loading system

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2720]
# Introduction
The current plugin API requires a god object in the plugin (known as the "main class") that programatically activates components of the plugin, such as commands, event handlers, etc. This is both inconvenient and not a good design pattern.

# Proposal
This issue proposes to prohibit the use of a plugin main class. Instead, multiple components of a plugin should be registered separately.

## Commands
To start with, extension to command registration should be introduced.
```yaml
name: NewEconomy
main: SOFe\NewEconomy\Main
commands:
  pay:
    description: Pays money
    class: \Commands\PayCommand
```

The `class` attribute can be resolved relative to the plugin main class, becoming `SOFe\NewEconomy\Commands\PayCommand`

## Events
```yaml
name: NewEconomy
main: SOFe\NewEconomy\Main
events:
  pocketmine\event\player:
    PlayerLoginEvent:
      class: \LoginHandler
      priority: MONITOR
      
    PlayerJoinEvent: \JoinHandler
```

Alternatively, traditional listeners can be registered in an array:
```yaml
listeners:
  - \EventListener
  - \OptionalEventListener
```
It is possible to support both approaches.

## Other components
The plugin may still declare persistent objects that persist throughout the lifetime of the server (not considering /reload in this proposal)
Instead of declaring a single main class to manage everything, plugins should be encouraged to use singleton structure, which could be initialized with an `::init` public static function:
```yaml
components:
  - \DataProvider
  - \libs\SOFe\Libkinetic\KineticManager # bonus: we can initialize libraries!
```

Instead of accessing these components via the plugin main class, other components of a plugin should access it via singleton pattern. This prevents passing the main class around and leading to an enormous god object that with a lot of verbosity like Server.php

# Concerns
## Configurability
To allow certain values (such as command names) to be configurable, allow a special dummy syntax that would get converted into a lazily loaded config value.
For instance:
```yaml
commands:
  $commands.pay:
    description: Pays money
    class: \Commands\PayCommand
```

This will load the nested value `commands.pay` from the default config (or otherwise specified) as the command name.

## I18n
Well... PocketMine i18n API for plugins is almost non-existent. But keep in mind to reserve room to improve this.

## Framework support
Plugins should still be allowed to programatically do the following things (registering commands, events, etc.)
In particular, libraries should be allowed to use plugin.yml as a way of activating library components.

## Backward compatibility
The old `main` attribute could be handled as a plugin component. But this is not the main class that represents the Plugin. The Plugin should be a final data class that only represents the data available in relation to the plugin, but it should not be mixed with the API of the plugin itself.
