### ISSUE TITLE
[BUG:] XUID does not match (possible impersonation attempt)

### ISSUE THREAD

**Issue by xXhen2527Xx** [pmmp/PocketMine-MP#4580]
### Issue description

- Expected result: `XUID does not match (possible impersonation attempt)` when you log in into game
- Actual result: When i joined via `Servers Tab`, because its not popouting on `Friends Tab` and when i want to see on ingame its kick me, says message `"XUID does not match (possible impersonation attempt)"`

### Steps to reproduce the issue
1. I try to sign out and sign in on my xbox account, its continues to say `XUID does not match (possible impersonation attempt)`
2. When is change `server.properties` on `xbox-auth=false` its continues `XUID does not match (possible impersonation attempt)` when i logged

### OS and versions
* PocketMine-MP: 3.24.5
* PHP: 8.0
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10

### Plugins
(31) Plugins

- If you remove all plugins, does the issue still occur? idk
- If the issue is **not** reproducible without plugins: 

### Crashdump, backtrace or other files
```
2021-11-17 [13:48:37] [Server thread/INFO]: [!] > Thank you for Joining to our Server!
2021-11-17 [13:49:25] [Server thread/INFO]: hen2527[/192.168.43.73:51222] logged out due to XUID does not match (possible impersonation attempt)
2021-11-17 [13:49:37] [Server thread/INFO]: [!] > Visit our website: url.com
2021-11-17 [13:50:23] [Server thread/INFO]: hen2527[/192.168.43.73:51222] logged out due to XUID does not match (possible impersonation attempt)
```

**Comment by dktapps** [comment]
This is expected. Disabling `xbox-auth` just allows non-xbox players to join the server. It doesn't allow them to use the same name as xbox players.

**Comment by xXhen2527Xx** [comment]
@dktapps
# Answer
yeah, i `xbox-auth=on` to `xbox-auth=off` idk, how i can join my own localhost server, which not popouting on Friends Tab, so i use `ipconfig` on cmd.exe, i copy my `ip4address` and entered it and i join, its says XUID does not match (possible impersonation attempt)

# Questions
- I want to see my server on Friends tab, How i can join, because theres no popouting PocketMine-MP, idk this is unexpected? HUH?
- How i can fix this bug `XUID does not match (possible impersonation attempt)` because its not working when i xbox-auth=off, and sign out on mcpe, but theres no popouting PocketMine-MP server in friend tab, and if you want to server tab i cant join, because i need to sign-in to my account

Issue: #4580

**Comment by xXhen2527Xx** [comment]
# New solutions!
When `xbox-auth=off` and seeing "XUID does not match (possible impersonation attempt)"
Try this solutions!

# How?
```yaml title="pocketmine.yml"
player:
  #Choose whether to enable player data saving.
  save-player-data: true
  #If true, checks that joining players' Xbox user ID (XUID) match what was previously recorded.
  #This also prevents non-XBL players using XBL players' usernames to steal their data on servers with xbox-auth=off.
  verify-xuid: false // set this to false to solve the problem!
  anti-cheat:
    #If false, will try to prevent speed and noclip cheats. May cause movement issues.
    allow-movement-cheats: true
```

Status: `Closed`/`Resolved`
I hope this helpful! 😄
