### ISSUE TITLE
Server is shutdown if a blacklisted plugin fails to load.

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5087]
### Issue description
Server is shutdown if a blacklisted plugin fails to load.

- Expected result: What were you expecting to happen?
The server ignores the plugin as was mentioned on #4951
- Actual result: What actually happened?
The server commits suicide.

### Steps to reproduce the issue
1. Get a plugin that will fail to load (example: incompatible protocol version)
2. Add the plugin to the blacklist
3. Start the server

### OS and versions

* PocketMine-MP: 4.4.0 (git hash: f2299a562f1ca11fb9edec75b182e47ad1771bba)
* PHP: 8.0.16
* Using JIT: No
* Server OS: Win10

### Plugins

Plugins (3): DevTools v1.15.0, PocketRadio v4.3.2, RankSystem v0.0.4
- If you remove all plugins, does the issue still occur?
Obviously not
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  Example of the `plugin.yml` of the plugin that caused the shutdown, reason: Unsupported protocol version
  ``` yaml  ---
  name: PocketRadio
  main: xenialdan\PocketRadio\Loader
  version: 4.3.2
  api: ["4.0.0"]
  mcpe-protocol: [388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,424,425,427,428,429,430,431,433,434,435,437,440,441,448,453,455,456,459,462,464,465,471,474,476,475,476,477,479,485,486,490,491,490,491,495,497,498]
  authors:
  - XenialDan
  prefix: "Radio"
  softdepend: [DEVirion]
  permissions:
    pocketradio.command:
      default: true
    pocketradio.command.radio:
      default: true
    pocketradio.command.radio.next:
      default: op
    pocketradio.command.radio.volume:
      default: true
  ...
  ```
