### ISSUE TITLE
Automatic permission declaration for plugin.yml commands

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#5306]
## Description
Currently, declaring a command via `plugin.yml` involves two steps:

1) Write the command description and usage message
2) Write the permission associated with the command

This is mildly annoying, because every command has to have a permission.

Most plugins use some standard format for their command permissions. DevTools, for example, prefixes all command permissions with `devtools.command.`.

## Before
It occurred to me that, instead of this:
```yml
commands:
 makeplugin:
  description: Creates a Phar plugin from one in source code form
  usage: "/makeplugin <pluginName>"
  permission: devtools.command.makeplugin

permissions:
 devtools.command.makeplugin:
  default: op
  description: "Allows the creation of Phar plugins"
```

it would be nice if the server could automatically declare the `devtools.command.makeplugin` permission. All it really needs is to know the default.

## After
```yml
commands:
 makeplugin:
  description: Creates a Phar plugin from one in source code form
  usage: "/makeplugin <pluginName>"
  permission-simple: op
```

With this, the server would automatically declare a `devtools.command.makeplugin` permission, using the default given by the `permission-simple` key.

This has a range of benefits:
- Standardisation of command permission prefixes. This is good for users, because consistency.
- Reduced boilerplate in `plugin.yml` to declare a command.
- Convenient, avoids abuse such as reusing the same permission multiple times (a trick that could be used to reduce the number of declarations)
