### ISSUE TITLE
Making a typo in plugin.yml isn't detected by pocketmine

### ISSUE THREAD

**Issue by nazthelizard122** [pmmp/PocketMine-MP#5466]
### Issue description

- Expected result: What were you expecting to happen
Honestly I don't know what to expect, "typo in yml" in the server log?
- Actual result: What actually happened?
Server carried on like nothing was wrong

### Steps to reproduce the issue
1. Make a typo in plugin .yml (for instance default =defaut)
2. Start the server
3. Observe that whatever the typo is in no longer works right

### OS and versions

* PocketMine-MP:4.12.1
* PHP:8.0.25
* Using JIT: no (delete as appropriate) 
* Server OS: Linux mint 
* Game version: iOS

### Plugins

This is the .yml with the typo I made https://discord.com/channels/373199722573201408/480650036972224513/1055653985702400021
This is in the Pocketmine discord in the support channel

SOFe suggested I open this issue

**Comment by dktapps** [comment]
This can be addressed by making certain keys mandatory.

A more complete fix would be to only allow a specific subset of keys, but that's a much more disruptive change.

Relates to #2635

**Comment by dktapps** [comment]
Related `plugin.yml` for posterity:

```yml
name: ui_test2
version: 0.0.1
main: naz\ui_test2\Main
api: 4.12.1
src-namespace-prefix: naz\ui_test2
commands:
    testui:
        description: test the ui
        usage: "/testui"
        permission: testuiperm.cmd
        permission-message: "no perms lol"
permissions:
    testuiperm.cmd:
        description: "test ui"
        defaut: true
```
