### ISSUE TITLE
Add ability to lock dependencies' version of the plugin

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#5959]
## Description
Add ability to lock dependencies' version of the plugin.

For example, like this.
```yml
name: TestPlugin
author: alvin0319
version: 1.0.0
api: 5.0.0

depend:
  Capital: 0.1.2
  DevTools: 1.17.0
```

## Justification
While plugins can do a version check something like `version_compare(Plugin->getDescription()->getVersion(), "...")`, I think there should be a core-level lock that prevents plugin from loading if dependency version doesn't fit.

## Alternative methods
You can check version using `version_compare()`, or implement [Capital-like API provider](https://github.com/SOF3/Capital/blob/d7006e951b63bc423b997d372a58e43eedeefd61/src/SOFe/Capital/Di/SingletonTrait.php#L48-L64)
